[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
# Environment variables will be set in Railway dashboard
# GEMINI_API_KEY = "your-gemini-api-key"
# OPENAI_API_KEY = "your-openai-api-key"
